### ISSUE TITLE
Problem: Preview file on appraisal tab broken

### ISSUE THREAD

**Issue by kellyannewithane** [artefactual/archivematica#951] opened 2018-03-06 19:18 UTC
On am17x.qa, transfer name: SunnySturgeon. 
Can't preview a file on Appraisal tab.  Confirmed it works in 1.6.1
Can still download but not preview in the preview window.

**Comment by ross-spencer** [comment] 2018-03-06 20:06
@kellyannewithane I was being nosy, and wanted to see if there was a Javascript error, but couldn't see one. Is this all that you're seeing?

![image](https://user-images.githubusercontent.com/1880412/37055512-ce2b4006-21e6-11e8-8437-af4d8906cf64.png)

**Comment by kellyannewithane** [comment] 2018-03-06 20:54
be nosy, all good!  you need to select file list as well like this




Regards,

Kelly Stewart

Systems Archivist
Artefactual Systems <https://www.artefactual.com/>
604-527-2056 <(604)%20527-2056>

**Comment by ross-spencer** [comment] 2018-03-06 21:17
I see! (or don't see as it were given the ticket!)

![image](https://user-images.githubusercontent.com/1880412/37058857-afca8c66-21f0-11e8-9578-5be58f41cc71.png)

No JS error there either, will need to check the server logs.

**Comment by ross-spencer** [comment] 2018-03-09 08:14
Duplicate of #884

**Closed by ross-spencer** 2018-03-09 08:14 UTC
Labels: bug
