### ISSUE TITLE
Problem: dashboard manage.py error on import

### ISSUE THREAD

**Issue by hakamine** [artefactual/archivematica#649] opened 2017-06-27 22:14 UTC
In https://github.com/artefactual/archivematica/pull/642 an archivematicaCommon module import was added to manage.py, but this is producing an error since the module can't be found even though the module path is specified using `--pythonpath`:

```
(archivematica-dashboard) vagrant@am-local:/usr/share/archivematica/dashboard$ ./manage.py --pythonpath=/usr/lib/archivematica/archivematicaCommon
Traceback (most recent call last):
  File "./manage.py", line 9, in <module>
    import elasticSearchFunctions
ImportError: No module named elasticSearchFunctions
```

To work around this need to do something like: 
```
(archivematica-dashboard) vagrant@am-local:/usr/share/archivematica/dashboard$ PYTHONPATH=/usr/lib/archivematica/archivematicaCommon ./manage.py
```

This problem is breaking deployments using https://github.com/artefactual-labs/ansible-archivematica-src.

Could an alternative to #642 be to use something like https://stackoverflow.com/a/37306165 instead of adding the import to the `manage.py` file?

**Comment by sevein** [comment] 2017-06-28 14:55
@hakamine, in #651 I'm reverting the commit as you suggested. We're doing this because we use `manage.py cmd --pythonpath=/dadada/archivematicaCommon` (not ideal). Importing modules from that package that early was forcing us to define `PYTHONPATH` in the environment, which would require making changes to our Ansible role. We've preferred to revert this commit for now and we'll solve this in a better way later, which I think can be done using django.settings in our ES module instead.

**Comment by sevein** [comment] 2017-10-21 19:07
@helenst, should we try to find a better place to set up the Elasticsearch client? We added it to wsgi.py and that seems to be working ok for Gunicorn but not when using manage.py. You fixed it in 834eb1c but we realized there was a problem with that solution - it makes use of the `elasticsearchFunctions` module before we give Django a chance to update the import search path when the user passes the [--pythonpath](`https://docs.djangoproject.com/en/1.8/ref/django-admin/#django-admin-option---pythonpath`) argument to manage.py, e.g. this argument is used by the [`django_manage`](http://docs.ansible.com/ansible/latest/django_manage_module.html) Ansible module (instead of using the `PYTHONPATH` environment string as we do in our Docker environment).

Would it work if we set up the ES client in our [MainAppConfig.read()](https://github.com/artefactual/archivematica/blob/qa/1.x/src/dashboard/src/main/apps.py#L7-L8) method? I'm hoping you can give that a try. I have a slight idea of how to reproduce the issue you were trying to solve but I suspect you can check this solution quicker than me - or maybe you can figure out a better solution.

**Comment by sevein** [comment] 2017-10-21 19:09
In any case I don't think this should block the release. This issue should only affects developers and we can always submit a fix to our branches. Bumping to 1.8.

**Comment by sevein** [comment] 2018-08-15 17:49
I'm closing this because the commit causing the issue [was reverted](https://github.com/artefactual/archivematica/commit/535b5fa1928854113c1d7c713992f30f164edc94#diff-42ee7bbc3b5eb815291a59a7890df339). Also the ES settings are now always populated via the settings module.

**Closed by sevein** 2018-08-15 17:49 UTC
