### ISSUE TITLE
Issue: MediaInfo and/or MediaConch causing invalid METS

### ISSUE THREAD

**Issue by sromkey** [artefactual/archivematica#1027] opened 2018-03-28 20:26 UTC
When validating the METS this error is occurring:

line 32, column 39: cos-nonambig: "https://mediaarea.net/mediainfo":Matrix_Channels and "https://mediaarea.net/mediainfo":Matrix_Channels (or elements from their substitution group) violate "Unique Particle Attribution". During validation against this schema, ambiguity would be created for those two particles.

@ablwr speculated that this might be caused by running mediainfolib 17.12 and mediaconch 18.03

**Comment by ablwr** [comment] 2018-03-28 20:30
Let me (try to) summarize what I said yesterday...

The METS sample file in question cites MediaInfo 4 times in the process:

Line 546, in amdSec_2  
Line  1417, in amdSec_4  
Line  2135, in amdSec_6  
Line  3085, in amdSec_8  

But, as noted, all in different sections for four different assets. I speculated that it could be firing twice and only writing once, and therefore causing the error.

And yeah, it could be that both are trying to carry the same namespace/ID and the process that writes the METS does not like that. Nesting one of these one level deeper would resolve the issue, or specifying a different namespace. 

But I haven't dug into and gotten more context into the issue, so that's all just speculation on my part!

**Comment by jrwdunham** [comment] 2018-03-28 23:50
I re-ran the DemoTransfer on a fresh current stable/1.7.x deploy—one with MediaInfo 18.03 and MediaConch 18.03 installed—and confirmed two things:

1. the same METS invalid issue arises as listed above
2. the validation PREMIS event(S) list MediaConch 18.03 in their eventDetail elements.

**Comment by jrwdunham** [comment] 2018-03-29 00:15
It looks like this may be being caused by the upgrade to MediaConch v. 18.03, which caused an [upgrade to MediaInfo v. 18.03](https://github.com/artefactual/archivematica/pull/1010/files#diff-5dafa6a4c747e0e4507e9c245e6006ecR91).

Now when we validate an Archivematica METS, the XMLSchema validation of the <MediaInfo> block in `<premis:objectCharacteristicsExtension>` is failing because of an issue in mediainfo_2_0.xsd: the problem seems to be that there are two identical elements contained within one `<xsd:choice>` element; the following occurs twice:

    <xsd:element name="Matrix_Channels" minOccurs="0" maxOccurs="1" type="xsd:integer"/>

Compare the `mediainfo_2_0.xsd` file referenced in our AIPs now to the `mediainfo.xsd` file referenced previously:

- https://mediaarea.net/mediainfo/mediainfo_2_0.xsd
- https://mediaarea.net/mediainfo/mediainfo.xsd

**Comment by ablwr** [comment] 2018-03-29 00:20
Thanks for this investigation @jrwdunham! 😨 

I opened an Issue in the corresponding MediaInfo library [here](https://github.com/MediaArea/MediaAreaXml/issues/36) and a PR to presumably patch it [here](https://github.com/MediaArea/MediaAreaXml/pull/37).

**Comment by ablwr** [comment] 2018-03-29 13:47
After merge and resolution of above issue, I tested again and all seems well re: this particular validation issue.

**Comment by sromkey** [comment] 2018-08-15 20:47
Unfortunately this is cropping up in installations of 1.7.x as well as qa/1.x

**Comment by sromkey** [comment] 2018-09-10 21:35
@sevein if you could look into this please as a precursor to fixing METS in the Dataverse branch.

**Comment by ablwr** [comment] 2018-09-11 15:44
This seems to have been related to a deployment issue on MediaArea's side and is now fixed in their XSD [here](https://mediaarea.net/mediainfo/mediainfo_2_0.xsd), which isn't tied to a release.  Now we can test!

**Closed** 2018-11-22 16:12 UTC
Labels: Status: verified
