### ISSUE TITLE
Problem: unable to update ss url in dashboard

### ISSUE THREAD

**Issue by scollazo** [artefactual/archivematica#861] opened 2017-12-20 19:02 UTC
In certain conditions, after accidentally misentered the storage service URL in the dashboard, you can't update it.

The dashboard log shows the following errors:
<pre>
HTTPError: 404 Client Error: NOT FOUND for url: http://localhost:8001/api/v2/pipeline/823c3af0-7940-46cb-8ec2-87a8759566fc/
ERROR     2017-12-05 18:39:15  archivematica.dashboard:views:transfer_source_locations:59:  Error retrieving source directories
Traceback (most recent call last):
  File "/usr/share/archivematica/dashboard/components/transfer/views.py", line 56, in transfer_source_locations
    return helpers.json_response(storage_service.get_location(purpose="TS"))
  File "/usr/lib/archivematica/archivematicaCommon/storageService.py", line 149, in get_location
    pipeline = _get_pipeline(get_setting('dashboard_uuid'))
  File "/usr/lib/archivematica/archivematicaCommon/storageService.py", line 123, in _get_pipeline
    response.raise_for_status()
  File "/usr/share/python/archivematica-dashboard/lib/python2.7/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: NOT FOUND for url: http://localhost:8001/api/v2/pipeline/823c3af0-7940-46cb-8ec2-87a8759566fc/
WARNING   2017-12-05 18:39:21  archivematica.common:storageService:_get_pipeline:122:  This Archivematica instance is not registered with the storage service or has been disabled.
WARNING   2017-12-05 18:39:21  archivematica.common:storageService:_get_pipeline:125:  Error fetching pipeline
Traceback (most recent call last):
  File "/usr/lib/archivematica/archivematicaCommon/storageService.py", line 123, in _get_pipeline
    response.raise_for_status()
  File "/usr/share/python/archivematica-dashboard/lib/python2.7/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: NOT FOUND for url: http://localhost:8001/api/v2/pipeline/823c3af0-7940-46cb-8ec2-87a8759566fc/
WARNING   2017-12-05 18:40:24  archivematica.common:storageService:_get_pipeline:122:  This Archivematica instance is not registered with the storage service or has been disabled.
WARNING   2017-12-05 18:40:24  archivematica.common:storageService:_get_pipeline:125:  Error fetching pipeline
Traceback (most recent call last):
  File "/usr/lib/archivematica/archivematicaCommon/storageService.py", line 123, in _get_pipeline
    response.raise_for_status()
  File "/usr/share/python/archivematica-dashboard/lib/python2.7/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: NOT FOUND for url: http://127.0.0.1:8001/api/v2/pipeline/823c3af0-7940-46cb-8ec2-87a8759566fc/
WARNING   2017-12-05 18:40:30  archivematica.common:storageService:_get_pipeline:122:  This Archivematica instance is not registered with the storage service or has been disabled.
WARNING   2017-12-05 18:40:30  archivematica.common:storageService:_get_pipeline:125:  Error fetching pipeline
Traceback (most recent call last):
  File "/usr/lib/archivematica/archivematicaCommon/storageService.py", line 123, in _get_pipeline
    response.raise_for_status()
  File "/usr/share/python/archivematica-dashboard/lib/python2.7/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: NOT FOUND for url: http://127.0.0.1:8001/api/v2/pipeline/823c3af0-7940-46cb-8ec2-87a8759566fc/
WARNING   2017-12-05 18:42:10  archivematica.common:storageService:_get_pipeline:122:  This Archivematica instance is not registered with the storage service or has been disabled.
WARNING   2017-12-05 18:42:10  archivematica.common:storageService:_get_pipeline:125:  Error fetching pipeline
Traceback (most recent call last):
  File "/usr/lib/archivematica/archivematicaCommon/storageService.py", line 123, in _get_pipeline
    response.raise_for_status()
  File "/usr/share/python/archivematica-dashboard/lib/python2.7/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: NOT FOUND for url: http://127.0.0.1:8001/api/v2/pipeline/823c3af0-7940-46cb-8ec2-87a8759566fc/
</pre>

This happened in a centos 1.7 rpm install, more info at https://github.com/artefactual/archivematica/issues/810#issuecomment-350098679

**Comment by sevein** [comment] 2017-12-20 20:48
Can you try setting it up again from `/installer/storagesetup/`?

**Comment by jpellman** [comment] 2017-12-21 17:43
Hi,

Sorry for opening a duplicate issue for this (#869) - the action item from our last meeting fell of my radar a bit and I didn't notice that separate issue had already been filed.  One clarification- this did not occur using an Archivematica 1.7 RPM (it looks like the initial comment might have been meant to read "centos 7.1 rpm" and the version number was a CentOS version number instead of an archivematica version number).  This was using the Archivematica 1.8 RPMs provided in the documentation [here](https://www.archivematica.org/en/docs/archivematica-1.8/admin-manual/installation/installation/#installation).  Also, what was the resolution of this?  I see that it's been closed but I don't see any details concerning how it was fixed or the current state of this bug.

**Comment by kellyannewithane** [comment] 2017-12-21 21:28
Hi @jpellman, it looks to us like what happened is at the Archivematica installer page you entered an incorrect storage service URL.  If you do that you won't be able to change the URL in the dashboard, unfortunately.  You can see in the above log output that the dashboard can't find the storage service (those 404 Client errors).  

You can see the documentation for this here: https://www.archivematica.org/en/docs/storage-service-0.10/administrators/#archivematica-configuration

**Comment by jpellman** [comment] 2017-12-22 15:51
Thanks @kellyannewithane - that's exactly what happened.  I was performing step 3 of the post-installation instructions [here](https://www.archivematica.org/en/docs/archivematica-1.8/admin-manual/installation/installation/#post-install-config) and misentered the storage service URL.  I then corrected the storage service URL from within the dashboard administrative panel (i.e., why the 404 error changed from localhost to 127.0.0.1 in the log; note also that these are only the last two 404 errors from in the logs- I tried changing the storage service URL a couple times before)  , which is what I thought the error below was directing me to do:

```
Storage server inaccessible. Please contact an administrator or update storage service URL below.
```

The imperative _update storage service URL_, coupled with a storage service URL field in the administrative panel, implies that this is something a naive user should be able to do within the dashboard.  If I'm understanding the documentation linked correctly, the issue is that after you misenter the storage service URL on initial setup the dashboard's UUID isn't registered as a pipeline in the storage service.  I might be wrong (given my ignorance of the dashboard codebase), but it sounds like what is happening is that when you update the storage service URL in the admin panel, it switches the URL in the panel config but doesn't go one step further and register the dashboard UUID as a pipeline in the storage service operating at the freshly designated URL.  Does this sound right or am I missing something?

**Comment by jpellman** [comment] 2018-01-04 19:59
Hi- I just wanted to check in on this issue now that we're in a new year!  Does my understanding of this storage server / dashboard issue jibe with what's actually occurring?

**Comment by sevein** [comment] 2018-01-22 23:19
> Does this sound right or am I missing something?

@jpellman I think that's pretty accurate. The easiest way to get around this is to launch the web installer manually, e.g.: http://host:port/installer/storagesetup/ and introduce the connection details again. It's a workaround but in my opinion it could be enough for AM17.

In a future release we could update the settings form with a new checkbox that allows the user to trigger the pipeline registration. Or perhaps that should be always done in an idempotent manner which would be possible because the SS API can tell us if it knows about a particular pipeline given its UUID.

**Comment by jhsimpson** [comment] 2018-01-23 00:18
sevein - I think there are 4 options based on what you are saying:  

**option 1** - (launch the web installer url to trigger pipeline registration manually) - there is no indication in the UI that this step is necessary, so I think we would have to add some text that appears after the ss location is changed, with a link to that url, or some text that says 'register this pipeline in storage service'.

**option 2** - (add a checkbox to the config page to trigger pipeline registration) - needs a code change to implement

**option 3** - (trigger pipeline registration automatically when the config page is updated) - also needs a code change.

**option 4** - (do nothing) no code change in this repo - but add some text to the documentation describing the work around (i.e. how to call the web installer manually)

I prefer Option 3.  It would require testing, to confirm that the call is truly idempotent, but I think we are pretty confident that it already is, so that does not seem like a big hurdle to me.

The other options require the user to take extra steps, which doesn't seem useful - there is no human decision to make.  It would always be 'if you change this text box, then also do this other thing'.  Seems better to automate it.

If there is a chance that option 3 is not completely idempotent, then it increases risk of a regression for 1.7, and in that case I agree about delaying the change until after the 1.7 release.  But I don't think that's the case, so I suggest option 3.

**Comment by sevein** [comment] 2018-01-23 00:25
Ok I'll do this tomorrow.

**Comment by sevein** [comment] 2018-01-30 15:54
#899 is now merged.

**Comment by jpellman** [comment] 2018-02-02 20:55
For review by @cul-archivematica.

**Closed** 2018-02-06 20:27 UTC
Labels: CUL: phase 1, Columbia University Library, Review
