### ISSUE TITLE
clamdscan problems with accented chars

### ISSUE THREAD

**Issue by scollazo** [artefactual/archivematica#740] opened 2017-09-29 17:41 UTC
Clamdscan chokes on files with accented chars ( áéíóú , and others)

<pre>
Traceback (most recent call last):
  File "/usr/lib/archivematica/MCPClient/clientScripts/archivematicaClamscan.py", line 118, in <module>
    sys.exit(main(fileUUID, target, date))
  File "/usr/lib/archivematica/MCPClient/clientScripts/archivematicaClamscan.py", line 92, in main
    result = client.scan(target)
  File "/usr/share/python/archivematica-mcp-client/local/lib/python2.7/site-packages/clamd/__init__.py", line 114, in scan
    return self._file_system_scan('SCAN', file)
  File "/usr/share/python/archivematica-mcp-client/local/lib/python2.7/site-packages/clamd/__init__.py", line 154, in _file_system_scan
    self._send_command(command, file)
  File "/usr/share/python/archivematica-mcp-client/local/lib/python2.7/site-packages/clamd/__init__.py", line 229, in _send_command
    concat_args = ' ' + ' '.join(args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 114: ordinal not in range(128)
</pre>

**Comment by sevein** [comment] 2017-09-29 18:01
Could you include the values of `clamav_server` and `clamav_pass_by_reference`, please?

**Comment by jrwdunham** [comment] 2017-09-30 00:10
In order to re-create this issue, it seems that MCPClient/lib/settings/common.py must have `CLAMAV_PASS_BY_REFERENCE` set to `True`.

I tried to re-create this issue on a Vagrant/Ansible deploy and had frustrations with clamscan having insufficient permissions:

    archivematicaClamscan.py: INFO      2017-09-29 23:02:03,907  archivematica.mcp.client.clamscan:main:110:  Clamd state=ERROR - Can't open file or directory

However, when testing with a Python script using the `clamd` (python-clamd) module and files with accented characters, I was able to recreate the issue and trigger a `UnicodeDecodeError`. It would seem that  this issue could be fixed by decoding `target` to Unicode prior to calling [`ClamdUnixSocket().scan(target)`](https://github.com/artefactual/archivematica/blob/qa/1.x/src/MCPClient/lib/clientScripts/archivematicaClamscan.py#L92):

    if mcpclient_settings.CLAMAV_PASS_BY_REFERENCE:
        if isinstance(target, str):
            target = target.decode('utf8')

The issue seems to be ultimately being caused by python-clamd calling `from __future__ import unicode_literals` and then calling [`concat_args = ' ' + ' '.join(args)`](https://github.com/graingert/python-clamd/blob/master/src/clamd/__init__.py#L231). This will raise a `UnicodeDecodeError` if there are bytestrings in `args`.

In order to sidestep the permissions issue, the next steps in fixing this would seem to be one of the following:

1. test the above fix on a Docker deploy
2. set `CLAMAV_SERVER` to a `host:port` value so that the client is built with `ClamdNetworkSocket`.

sevein also suggests looking into using [pyclamd](https://bitbucket.org/xael/pyclamd/src/2089daa540e1343cf414c4728f1322c96a615898/pyclamd/pyclamd.py?at=default&fileviewer=file-view-default) instead of the current [python-clamd](https://github.com/graingert/python-clamd).

**Comment by sevein** [comment] 2017-09-30 10:39
> 2. set CLAMAV_SERVER to a host:port value so that the client is built with ClamdNetworkSocket

I believe that's not going to solve your permission issue. Ultimately you're asking clamav to read some files given their locations, and that's where the permission issue roots regardless the transport used to send the command (i.e. unix or tcp). Does that make sense?

It'd be nice that we used `clamav_pass_by_reference = True` in our package-based installation but AM 1.6 never did such thing and antivirus scanning wasn't a bottleneck AFAIK so I wouldn't bother for now, unless @scollazo wants to have the clamd user added to the archivematica group or something like that.

> It would seem that this issue could be fixed by decoding target to Unicode prior to calling ClamdUnixSocket().scan(target).

Good catch. That seems like a good idea. Correct me if I'm wrong but shouldn't we be using Unicode strings at that point anyways as a general practice?

**Comment by jrwdunham** [comment] 2017-10-02 15:27
> I believe that's not going to solve your permission issue. Ultimately you're asking clamav to read some files given their locations, and that's where the permission issue roots regardless the transport used to send the command (i.e. unix or tcp). Does that make sense?

@sevein Yeah, makes sense. It was a shot in the dark. For the record, I did try adding the clamav user to the archivematica group and also recursively changing the shared directory to be very permissive. None of that seemed to work.

> Correct me if I'm wrong but shouldn't we be using Unicode strings at that point anyways as a 
general practice?

Yes, but that would mean pulling on a very long string I think. The `target` var is type `str` when passed to archivematicaClamscan.py. The `target` param passed to archvematicaClamscan comes from the "%relativeLocation%" variable in the Unicode string `StandardTaskConfig.arguments`. However, as soon as linkTaskManagerFiles.py calls `ReplacementDict.replace` [arguments is changed from `unicode` to `str`](https://github.com/artefactual/archivematica/blob/qa/1.x/src/archivematicaCommon/lib/dicts.py#L193-L199).

**Comment by sevein** [comment] 2017-10-03 09:49
I would think that `target` is always a sequence of bytes because it's a command-line argument (`sys.argv[2]`). I think we have to assume that it's arbitrary undecodable data, but we can try to apply the utf-8 encoding and the locale's encoding as a fallback. Would that be good enough?

**Comment by sevein** [comment] 2017-10-03 22:06
https://github.com/JiscRDSS/rdss-archivematica/issues/57

**Comment by jrwdunham** [comment] 2017-10-04 19:17
> I would think that target is always a sequence of bytes because it's a command-line argument 

Yeah, that makes sense. See https://github.com/artefactual/archivematica/pull/743

**Closed** 2017-10-05 14:05 UTC

**Comment by kellyannewithane** [comment] 2017-10-11 20:15
on augustus, DCTest_2, fail at virus scan


archivematicaClamscan.py: ERROR     2017-10-11 18:57:46,681  archivematica.mcp.client.clamscan:main:95:  Unexpected error scanning: /var/archivematica/sharedDirectory/currentlyProcessing/DCTest_2-0b1370c9-2078-4283-9a24-6dae1ccdc309/objects/71_Volcán.mov
Traceback (most recent call last):
  File "/usr/lib/archivematica/MCPClient/clientScripts/archivematicaClamscan.py", line 93, in main
    result = client.instream(open(target))
  File "/usr/share/python/archivematica-mcp-client/local/lib/python2.7/site-packages/clamd/__init__.py", line 190, in instream
    self.clamd_socket.send(size + chunk)
error: [Errno 32] Broken pipe
archivematicaClamscan.py: INFO      2017-10-11 18:57:46,682  archivematica.mcp.client.clamscan:record_event:56:  Recording event for fileUUID=51c37bb7-6780-49b4-b987-40be2e292d6e outcome=Fail

**Comment by sevein** [comment] 2017-10-11 22:17
@kellyannewithane, I believe the issue with accents is solved. But there is a problem with large files that I've described here: https://github.com/artefactual/archivematica/issues/753.
