### ISSUE TITLE
Problem: Usability: pressing Enter in ArchStore search form searches for previous term

### ISSUE THREAD

**Issue by jrwdunham** [artefactual/archivematica#1058] opened 2018-04-20 21:48 UTC
To re-create:

1. Search for an AIP UUID in the Archival Storage tab.
2. Change the AIP UUID search term to a different one and hit Enter.
3. Expect to see the initial UUID searched for.

Correct behaviour would be to see the second UUID being searched for.

**Comment by ross-spencer** [comment] 2018-12-17 11:16
I feel like this is a duplicate of https://github.com/artefactual/archivematica/issues/1044 what do you think @jrwdunham? Please feel free to re-open if marked incorrectly.

**Closed by ross-spencer** 2018-12-17 11:16 UTC

**Comment by ross-spencer** [comment] 2018-12-18 08:42
See also: https://github.com/archivematica/Issues/issues/271
