### ISSUE TITLE
Problem: Resource icon on ArchivesSpace pane of Appraisal tab not consistent

### ISSUE THREAD

**Issue by kellyannewithane** [artefactual/archivematica#859] opened 2017-12-20 18:35 UTC
When a new resource shows up on the ArchivesSpace pane of the Appraisal tab, the icon is a document.  When a digital object is added to that resource the icon changes from a document to a folder.

**Comment by ross-spencer** [comment] 2017-12-20 19:05
Partial duplicate of #760

**Closed by ross-spencer** 2017-12-20 19:05 UTC
Labels: duplicate
