### ISSUE TITLE
Problem: there is no way to stop passing output streams from MCPClient worker processes to the MCPServer scheduler

### ISSUE THREAD

**Issue by kellyannewithane** [artefactual/archivematica#763] opened 2017-10-18 18:36 UTC
Columbia University Library (CUL) would like to increase scalability and reduce performance problems by making it possible to configure Archivematica to stop MCPClient worker processes from passing very large stdout/stderr streams back to the MCPServer (Gearman) task scheduler.

While it would be nice to send the MCPClient worker output streams to some other storage service (e.g., a document store), CUL and Artefactual have opted to forego this option and instead simply allow for a binary configuration setting, allowing for the following two options:

1. retain output streams, i.e., by continuing to send them from worker to scheduler and storing them in the MCP database; or
2. discard output streams entirely, except for stderr which should be saved in the same way as before for debugging failures; see https://github.com/artefactual/archivematica/issues/909.

Expected results would be: 
- decrease in total processing time. This was borne out by [AM acceptance tests PR 47](https://github.com/artefactual-labs/archivematica-acceptance-tests/pull/47) which showed a 6% reduction in total processing time for small AIPs (with larger AIPs expected to exhibit greater performance improvements).
- increase in number of files processed simultaneously
- increase in size of the largest file that can be processed

**Comment by sevein** [comment] 2017-10-23 16:12
Related: https://github.com/artefactual/archivematica/pull/580#issuecomment-310915756

**Comment by jrwdunham** [comment] 2018-02-22 23:00
The original title of this issue was "Problem: Need a way to log task outputs outside the database". I changed it (and the description above) to reflect the change in our understanding of the issue and in our approach to solving it.

**Comment by jrwdunham** [comment] 2018-02-24 00:02
Note: a solution to this issue will require having the "no capture" option continue to capture (i.e., pass back to MCPServer and store in the database) the *stderr* of client script executions ONLY IF the client script has failed, i.e., returned a non-zero status code. Cf. the closed issue https://github.com/artefactual/archivematica/issues/909.

**Comment by jrwdunham** [comment] 2018-05-03 22:48
@sevein @ross-spencer @scollazo @hakamine @jhsimpson We have an unresolved issue blocking progress on the 1.7.1 release that we would like input on. The heart of the problem is that we need to get [AM PR 1078](https://github.com/artefactual/archivematica/pull/1078) merged into stable/1.7.x but the incoming branch contains a strange commit history in which one commit (21d0fbbe0c8cb1b4b9822682dcbb14391ab8bd67) puts the system into a non-functioning state. This is complicated by the fact that our qa/1.x branch already has the commits in question in it.

Justin has proposed the following options for how to proceed:

1. commit into stable/1.7.x as is (using prs in their current state
2. squash or otherwise refactor these 3 PR's so that the history in
   stable/1.7.x is different, but don't rewrite history in qa/1.x
3. squash in stable/1.7.x, rewrite history in qa/1.x to match
4. squash in stable/1.7.x, and then stop using qa/1.x - start a new qa/1.8.x
   branch, that is forked from stable/1.7.x (i.e. has identical history) and
   has the new commits added to it from qa/1.x that are missing

We are leaning towards option (4) but would like to have a better understanding of the ramifications. Please post your thoughts on the issue here. Thanks!

**Comment by sevein** [comment] 2018-05-04 00:49
I don't think that having an identical history is that important after all. They're almost like different products, two branches that are never going to meet again in the future. Cryptographically, their commits are never going to be the same regardless their metadata. So I'd rather have a clean history in stable/1.7.x now that you have another to do it. To me #4 is a bit too much of juggling and we have a bunch of PRs and links all around pointing to commits that wouldn't be there anymore. Isn't #4 just the equivalent of rewriting the whole branch since stable/1.7.x was created? That doesn't sound like a good idea to me.

**Comment by jhsimpson** [comment] 2018-05-04 01:03
I have a couple of arguments in favour of option 4)

- the commit history in stable/1.7.x is very different than commit history that will end up in stable/1.8.x (if we don't use option 4) . This is because we have had a stable/1.7.x branch for longer than expected, and many commits have been cherry-picked into both branches.

- option 4 allows us to decide what should be in 1.7.2 (there are a few bug fixes in qa/1.x, that could easily be in a 1.7.2 release, but we don't want new features that are in qa/1.x getting into a release until 1.8.0)

- option 4 allows commits to be squashed to provide a cleaner commit history.  There are a number of cases where several commits were added to qa/1.x to fix bugs introduced in earlier qa/1.x only commits.  I think if a bug is introduced in one commit and then fixed in another, and neither of those commits were in a public release, it is reasonable to want to squash them down to a single commit.

**Comment by jhsimpson** [comment] 2018-05-04 01:07
@seveins point is a fair one, option 4 might be more work than it is worth.  Although I did look through the commits in both branches, and documented the differences here:

https://docs.google.com/document/d/1Dp6f2oT5C4KLWSXflLG4wlGdWTNoy0sL96DwfKvlw-w/edit

If we don't use option 4, then there are 5 commits in stable/1.7.x that are missing from qa/1.x, that would need to get added.  

@sevein do you prefer one of the other options? Or is there an option that is not listed yet?

**Comment by ross-spencer** [comment] 2018-05-04 06:37
I think option 2 as well for similar reasons if I understand correctly. If I try to write what I think is situation is that supports 2: `1.7.x` is the public release branch, and therefore becomes a sort-of reference branch where right now we have a chance to make sure the history of correct (and ensure it isn't in a broken state at any point). The `qa/1.x` branch is known to be our development branch, that is, not a reference branch for the community running Archivematica (as @sevein says, it is like a different product). It contains the entire commit history as we've developed features for any particular public release. Going forward (once option 2 is put into action) we will cherry-pick the five commits missing that are in `1.7.x` into `qa/1.x` and then mint a new `1.8.x` from `qa/1.x` closer to the time we need a `1.8.x`.

If that's correct - then :+1: 2

**Comment by jhsimpson** [comment] 2018-05-04 20:54
sounds like we are agreeing with option 2.  This was discussed outside github and is now the Official Plan.

**Closed** 2018-05-04 23:06 UTC
Labels: CUL: phase 2, Columbia University Library, Review
