### ISSUE TITLE
Assign checksums and file sizes to objects fails for files with backtick in name

### ISSUE THREAD

**Issue by kerim1** [artefactual/archivematica#922] opened 2018-02-13 14:02 UTC
The 'Assign checksums and file sizes to objects' step fails for certain files:

```
"%sharedPath%" --filePath "/data/work/sharedDirectory/01/currentlyProcessing/ARCH03161.dig3737-c6275d12-03dc-4b58-aee5-b4f940410000/data/(shared) Collectives, articulations, events, activities../Peasant Rights/X-Documents before 31-12-2015 Peasant Rights/Docs  2015 Peasant Rights/OEWG February 2015/05-Reaction to Chairperson\`s Report.docx" --fileUUID "None" --eventIdentifierUUID "%taskUUID%" --date "%date%"
```

```
archivematicaUpdateSizeAndChecksum.py: INFO      2018-02-13 13:05:43,017  archivematica.mcp.client.updateSizeAndChecksum:<module>:149:  Invoked as /usr/lib/archivematica/MCPClient/clientScripts/archivematicaUpdateSizeAndChecksum.py /data/work/sharedDirectory/01/ --filePath /data/work/sharedDirectory/01/currentlyProcessing/ARCH03161.dig3737-c6275d12-03dc-4b58-aee5-b4f940410000/data/(shared) Collectives, articulations, events, activities../Peasant Rights/X-Documents before 31-12-2015 Peasant Rights/Docs  2015 Peasant Rights/OEWG February 2015/05-Reaction to Chairperson\`s Report.docx --fileUUID None --eventIdentifierUUID fff42742-0d10-43ad-9e68-a947da5e3b94 --date 2018-02-13T13:05:42.485207+00:00.
usage: archivematicaUpdateSizeAndChecksum.py [-h] [-i FILE_UUID]
                                             [-p FILE_PATH] [-d DATE]
                                             [-u EVENT_UUID]
                                             sharedPath
archivematicaUpdateSizeAndChecksum.py: error: argument -i/--fileUUID: invalid <lambda> value: 'None'
```

All of the failing files seem to have one thing in common: all of their names contain a backtick: "Chairperson\\`s".  Could this somehow prevent the UUID from getting passed to archivematicaUpdateSizeAndChecksum.py?

Connected to: https://github.com/archivematica/Issues/issues/16

**Comment by ross-spencer** [comment] 2018-02-15 18:44
I can confirm I can see the same behaviour. It does seem to be the backtick causing the problem. I did a little investigation but haven't got to the root cause yet. I can see the Linux escape for the backtick in the database okay. I'm note sure if that has to be escaped further in MySQL as (``).

**Comment by lwo** [comment] 2018-03-02 10:55
Is there any progress on this? Or a way to get around the problem without renaming the file?

**Comment by kerim1** [comment] 2018-03-12 13:28
We notice the UUID is not passed along during the task creation in the MCP server due to this failing if statement: https://github.com/artefactual/archivematica/blob/qa/1.x/src/MCPServer/lib/unit.py#L67-L72 The file list contains the path without an escape character, while the path from the database does contain an escape character. We tried to apply a dirty fix, by replacing the ecaped backtick with a non-escaped backtick. This works in the sense that the UUID is now passed along the the client script. However, now the escape character itself is escaped too, causing it to fail anyway.

**Comment by ross-spencer** [comment] 2018-03-15 08:05
@kerim1 thanks for looking into this some more. I will focus on this some more tomorrow and think I've a few avenues to follow here. The file list comparison looks faulty and I need to understand how on the one hand we can have an escaped absolute path, and an un-escaped relative path/filename within a few function calls of each other. Perhaps there is some additional consistency to be found there. It could be the wrong avenue of course but will get back to you soon.

**Comment by ross-spencer** [comment] 2018-03-22 09:42
@kerim1 I took the opportunity to familiarise myself with the MCP Server. I've traced this issue back to just this single escape function here: https://github.com/artefactual/archivematica/blob/stable/1.7.x/src/archivematicaCommon/lib/archivematicaFunctions.py#L135

If I read this correctly, it means when we first pass this file into the database, which happens fairly late in the process: https://github.com/artefactual/archivematica/blob/stable/1.7.x/src/MCPClient/lib/clientScripts/archivematicaAssignFileUUID.py#L143

It is being put into the database escaped.

That means, when we come to supply the file's UUID to even just the next task in the chain, it can't be paired with the objects in the filesystem. You've already seen how Archivematica tries to assign the UUID here: https://github.com/artefactual/archivematica/blob/stable/1.7.x/src/MCPServer/lib/unit.py#L67

It has taken me a bit of time to understand different implications. As you can imagine there are a number of different effects of any change we make that we have to take into account.

* We can't easily modify `unit.py` to run a comparison against an escaped set of file paths. This would require duplicating the data structure used to store the current file list in that script, which seems inefficient, but it might be a sensible approach.

* We can't simply 'unescape' the filename before adding it to the database (as you've seen) as this seems to then create a double escaping issue - so some strange interchange of filesystem/database strings that shouldn't be happening.  

* We can possibly remove the call to replace the backtick in `archivematicaFunctions.py`. Simple testing on my deployment shows that this has no impact on either folders or files. If you wanted to give this a try in your QA environment, then just make sure to restart the MCP Server. If that were the solution for now, before releasing a fix into the world I would like to check what tests we can put in place to make sure AM still behaves as expected.

**Ultimately:**

* I believe the MCP Client UUID script shouldn't have the responsibility of making the call to update the database. Ideally a value would be sent back to the MCP server and it would be updated from there without the data having already been modified. A more complex fix might involve doing that. And as we've seen that might not be straightforward either.

* There are other patterns for looking after 'obscure' filenames in complex systems like Archivematica. Our code base seems to utilise some in a few in different ways, e.g. for encoding/decoding Unicode strings given certain client script requirements. An example of one alternative pattern, is some systems re-writing the filename with a form of UUID early, and repatriate it with the file at the end of processing - or on delivery. File naming conventions really only then need to be handled at the model/view layer and not in the interactions with the OS. In the future re-engineering this handling in AM might be an approach too. 

* Justin has suggested the possibility of the 'Clean Up Names' microservice being moved earlier in the workflow. I don't know the full extent of making that happen but this does handle bac-kticks and convert them to underscores. We can certainly investigate this further.

**Next steps**

The first step is to find an approach for now - I think we can try removing this line: https://github.com/artefactual/archivematica/blob/stable/1.7.x/src/archivematicaCommon/lib/archivematicaFunctions.py#L135 - I have observed that this works for folders and filenames. The rationale for escaping this character previously could have been for many reasons. It seems if it did affect any part of the Archivematica workflow previously, it is more robust now and so can deal with the character. 

We can look at longer term approaches afterwards.

**Comment by ross-spencer** [comment] 2018-04-05 10:38
@lwo @kerim1 hi both - thinking about ways forward and targeting a longer-term fix for this, did you manage to try the workaround to this with any success?

**Comment by lwo** [comment] 2018-04-05 13:27
I have not seen an error occur with any of our transfers that contain a backtick ever since... so I cannot refute it's success.

**Comment by ross-spencer** [comment] 2018-07-17 15:38
Reopening. The problem in archivematica/issues#16 seems to be related to a unicode handling regression not the backtick issue previously reported.

**Comment by ross-spencer** [comment] 2018-08-13 19:20
Resolved by https://github.com/archivematica/Issues/issues/16 so moving to in review. The specific comments about the fix are here: https://github.com/archivematica/Issues/issues/16#issuecomment-405802297

**Comment by peterVG** [comment] 2018-09-27 20:04
@ross-spencer am I correct to assume that this issue (or at least its fix) is a duplicate of https://github.com/archivematica/Issues/issues/16 ?

**Comment by ross-spencer** [comment] 2018-09-27 20:35
@peterVG :+1: 

(I had put a comment in #16 about that one superseding this one. Evidently I forgot to close this one following that.)

**Comment by peterVG** [comment] 2018-09-27 21:10
superseded by https://github.com/archivematica/Issues/issues/16

**Closed** 2018-11-22 16:06 UTC
Labels: IISH, Status: duplicate, Status: verified, Type: bug
