### ISSUE TITLE
Problem: Archivematica 1.7.0 and 1.7.1 making multiple copies of large transfers

### ISSUE THREAD

**Issue by jpellman** [artefactual/archivematica#1207] opened 2018-07-12 14:54 UTC
We noticed while running Archivematica 1.7.0 under Ubuntu 16.04 with a 351 GB transfer that instead of showing the transfer in the dashboard after one fully copy of it to /var/archivematica/sharedDirectory/tmp, Archivematica proceeds to make 9 additional full copies of the transfer to that same directory, for a total size of 3.4 TB.  

We were able to replicate this behavior under Archivematica 1.7.1 running under CentOS 7.  In the case of CentOS 7 at least, the transfer never appeared in the dashboard even after the 10 copies were made.

**Comment by sromkey** [comment] 2018-07-12 16:08
@jpellman Out of curiosity, what browser are you using? We're seen this happen in Firefox because it has a timeout (10 minutes-ish we think) and the process keeps restarting when it doesn't receive a response.

**Comment by jpellman** [comment] 2018-07-12 16:56
@sromkey We've been using Firefox.  Is there any way to verify that we're encountering the same phenomenon in the Archivematica dashboard/storage service/MCP logs?

**Comment by nickwilkinson** [comment] 2018-07-26 22:16
@jpellman I spoke with a few team members who've looked into this and it turns out another organization reported this issue about a year ago. From that investigation we found that Firefox has a 10 minute http long-lived-idle-time keep alive, so if the response from the transfer doesn't make it back in 10 minutes then the connection closes and it resubmits. That's why the duplicates start around 10 minutes apart. This would not happen if the response came back sooner than 10 minutes.

Chrome doesn't have this setting and it doesn't exhibit this timeout->resubmit behaviour. So as a workaround, you can either use Chrome or continue using Firefox provided you change this setting to greater than 10 minutes.

**Comment by sevein** [comment] 2018-07-27 20:40
FWIW this would not be a problem in our qa/1.x branch because the new Package API returns immediately.

**Comment by sevein** [comment] 2018-07-27 21:03
(regarding to my comment above, see related issue #1139)

**Comment by sevein** [comment] 2018-07-27 21:04
@jpellman one possible way to confirm it is to enable the access log in Gunicorn (both Dashboard and SS use it). There is a configuration file that ansible/packages should deploy in /etc IIRC.

**Comment by jpellman** [comment] 2018-07-27 21:09
The rsync commands are logged as having started approximately 10 minutes apart:

```
# In /digital/working/tmp
[jsp2205@ip-172-31-2-26 tmp]$ ls -lt
total 60
drwxrwx--- 3 archivematica archivematica 6144 Jul 10 11:24 tmpIqyjyj
drwxrwx--- 3 archivematica archivematica 6144 Jul 10 11:22 tmpzgrXyP
drwxrwx--- 3 archivematica archivematica 6144 Jul 10 11:21 tmpKmYyeb
drwxrwx--- 3 archivematica archivematica 6144 Jul 10 11:18 tmpEFkbGI
drwxrwx--- 3 archivematica archivematica 6144 Jul 10 11:13 tmpVcR66d
drwxrwx--- 3 archivematica archivematica 6144 Jul 10 11:06 tmpoZToUs
drwxrwx--- 3 archivematica archivematica 6144 Jul 10 10:56 tmpt9nfFn
drwxrwx--- 3 archivematica archivematica 6144 Jul 10 10:36 tmpl_qK8B
drwxrwx--- 3 archivematica archivematica 6144 Jul 10 10:10 tmpe_tA7s
drwxrwx--- 3 archivematica archivematica 6144 Jul 10 09:03 tmpisFA4N
drwx------ 2 archivematica archivematica 6144 Jun 30 11:23 fits.d1GPzn
drwx------ 2 archivematica archivematica 6144 Jun 30 08:48 fits.Vfl1a6
drwx------ 2 archivematica archivematica 6144 Jun 30 08:26 fits.q1atjA
drwx------ 2 archivematica archivematica 6144 Jun 30 08:04 fits.pKngEe
drwx------ 2 archivematica archivematica 6144 Jun 30 07:19 fits.UdZ10X
```

```
07/27 17:03:05 [jsp2205@connect: ~/unix5645/var/log/archivematica/storage-service]
$ for temp in tmpIqyjyj tmpzgrXyP tmpKmYyeb tmpEFkbGI tmpVcR66d tmpoZToUs tmpt9nfFn tmpl_qK8B tmpe_tA7s tmpisFA4N; do grep ${temp} storage_service_debug.log | grep "rsync command"; done
INFO      2018-07-09 14:01:32  locations.models.space:space:move_rsync:468:  rsync command: ['rsync', '-t', '-O', '--protect-args', '-vv', '--chmod=Fug+rw,o-rwx,Dug+rwx,o-rwx', '-r', '/digital/ingest/15000/RBML_spectator_images/.', '/digital/digital/working/tmp/tmpIqyjyj/15000_images_AWS_test_7_09/.']
INFO      2018-07-09 13:50:12  locations.models.space:space:move_rsync:468:  rsync command: ['rsync', '-t', '-O', '--protect-args', '-vv', '--chmod=Fug+rw,o-rwx,Dug+rwx,o-rwx', '-r', '/digital/ingest/15000/RBML_spectator_images/.', '/digital/digital/working/tmp/tmpzgrXyP/15000_images_AWS_test_7_09/.']
INFO      2018-07-09 13:38:49  locations.models.space:space:move_rsync:468:  rsync command: ['rsync', '-t', '-O', '--protect-args', '-vv', '--chmod=Fug+rw,o-rwx,Dug+rwx,o-rwx', '-r', '/digital/ingest/15000/RBML_spectator_images/.', '/digital/digital/working/tmp/tmpKmYyeb/15000_images_AWS_test_7_09/.']
INFO      2018-07-09 13:27:26  locations.models.space:space:move_rsync:468:  rsync command: ['rsync', '-t', '-O', '--protect-args', '-vv', '--chmod=Fug+rw,o-rwx,Dug+rwx,o-rwx', '-r', '/digital/ingest/15000/RBML_spectator_images/.', '/digital/digital/working/tmp/tmpEFkbGI/15000_images_AWS_test_7_09/.']
INFO      2018-07-09 13:16:05  locations.models.space:space:move_rsync:468:  rsync command: ['rsync', '-t', '-O', '--protect-args', '-vv', '--chmod=Fug+rw,o-rwx,Dug+rwx,o-rwx', '-r', '/digital/ingest/15000/RBML_spectator_images/.', '/digital/digital/working/tmp/tmpVcR66d/15000_images_AWS_test_7_09/.']
INFO      2018-07-09 13:04:43  locations.models.space:space:move_rsync:468:  rsync command: ['rsync', '-t', '-O', '--protect-args', '-vv', '--chmod=Fug+rw,o-rwx,Dug+rwx,o-rwx', '-r', '/digital/ingest/15000/RBML_spectator_images/.', '/digital/digital/working/tmp/tmpoZToUs/15000_images_AWS_test_7_09/.']
INFO      2018-07-09 12:53:19  locations.models.space:space:move_rsync:468:  rsync command: ['rsync', '-t', '-O', '--protect-args', '-vv', '--chmod=Fug+rw,o-rwx,Dug+rwx,o-rwx', '-r', '/digital/ingest/15000/RBML_spectator_images/.', '/digital/digital/working/tmp/tmpt9nfFn/15000_images_AWS_test_7_09/.']
INFO      2018-07-09 12:41:58  locations.models.space:space:move_rsync:468:  rsync command: ['rsync', '-t', '-O', '--protect-args', '-vv', '--chmod=Fug+rw,o-rwx,Dug+rwx,o-rwx', '-r', '/digital/ingest/15000/RBML_spectator_images/.', '/digital/digital/working/tmp/tmpl_qK8B/15000_images_AWS_test_7_09/.']
INFO      2018-07-09 12:30:34  locations.models.space:space:move_rsync:468:  rsync command: ['rsync', '-t', '-O', '--protect-args', '-vv', '--chmod=Fug+rw,o-rwx,Dug+rwx,o-rwx', '-r', '/digital/ingest/15000/RBML_spectator_images/.', '/digital/digital/working/tmp/tmpe_tA7s/15000_images_AWS_test_7_09/.']
INFO      2018-07-09 12:19:12  locations.models.space:space:move_rsync:468:  rsync command: ['rsync', '-t', '-O', '--protect-args', '-vv', '--chmod=Fug+rw,o-rwx,Dug+rwx,o-rwx', '-r', '/digital/ingest/15000/RBML_spectator_images/.', '/digital/digital/working/tmp/tmpisFA4N/15000_images_AWS_test_7_09/.']
```

Which indicates that we may have encountered the same bug as what you described.  Unfortunately, the test instance we were running this on is no longer active (terminated EC2 instance) so we can't try enabling access logs in Gunicorn.

**Comment by sromkey** [comment] 2018-08-31 22:00
Because this shouldn't be an issue in the qa branch, I'm closing this issue.

**Comment by jpellman** [comment] 2018-09-04 15:17
Can you leave this open until it's verified as fixed in one of the packaged versions?  I wouldn't consider this resolved until you can guarantee that no regressions have been introduced when the fix is merged from qa to the mainline branch.

**Comment by peterVG** [comment] 2018-10-17 19:43
So in recent tests with large transfers I can confirm that Firefox is no longer creating duplicate transfers in the `/var/archivematica/sharedDirectory/tmp` directory, as originally reported on this issue. However, in the 1.8 release there now seems to be a new, related issue so this one remain open in the meanwhile so that it can be fully tested once related fix is in. https://github.com/archivematica/Issues/issues/280

**Closed** 2018-11-22 16:05 UTC
Labels: Columbia University Library, Status: verified
