### ISSUE TITLE
Problem: Verify metadata directory checksums is failing

### ISSUE THREAD

**Issue by sallain** [artefactual/archivematica#873] opened 2018-01-04 21:17 UTC
On augustus, I selected a transfer that contains existing checksums (SampleTransfers/DemoTransfer). The transfer fails on the Verify transfer checksums microservice with the following errors:
```
/usr/lib/archivematica/MCPClient/clientScripts/archivematicaCheckMD5NoGUI.sh: line 41: sha256deep: command not found
/usr/lib/archivematica/MCPClient/clientScripts/archivematicaCheckMD5NoGUI.sh: line 44: sha256deep: command not found
```
The same error appears for md5 and sha1 checksums:

```
/usr/lib/archivematica/MCPClient/clientScripts/archivematicaCheckMD5NoGUI.sh: line 41: md5deep: command not found
/usr/lib/archivematica/MCPClient/clientScripts/archivematicaCheckMD5NoGUI.sh: line 44: md5deep: command not found
/usr/lib/archivematica/MCPClient/clientScripts/archivematicaCheckMD5NoGUI.sh: line 41: sha1deep: command not found
/usr/lib/archivematica/MCPClient/clientScripts/archivematicaCheckMD5NoGUI.sh: line 44: sha1deep: command not found
```

**Comment by scollazo** [comment] 2018-01-04 23:44
The hashdespp package in Ubuntu 16.04 doesn't have the /usr/bin/md5deep symlink. After creating them in augustus, the transfer works.

My question is why are we using md5deep, from the hashdeep package, instead of md5sum, the one that almost all systems have installed, and that is provided in the coreutils package. The output from the archivematica used commands is the same (unless for getting the program version)

We can fix it in the docs/packages/ansible scripts, or in the clientScript code. @sevein , what do you think?

**Comment by sevein** [comment] 2018-01-05 00:14
I think *deep was used because of the ability to run in recursive mode.

https://github.com/artefactual/archivematica/blob/stable/1.7.x/src/MCPClient/lib/clientScripts/archivematicaCheckMD5NoGUI.sh#L41

**Comment by scollazo** [comment] 2018-01-05 11:53
Created the symlinks in the ansible playbooks as a workaround ( https://github.com/artefactual-labs/ansible-archivematica-src/commit/882967dfbd1b7b449ba8c1529320c17f201e10e9 ), but I'm having second thoughts about it, as this change needs to be propagated to debian packages and manual installs too, and also, this can bring unexpected behaviour in future Ubuntu releases.

Using another approach, rebuilt the hashdeep package from Ubuntu 17.10 , that includes the md5deep links,  at https://github.com/artefactual-labs/am-packbuild/pull/105 .

Once this is approved I'll upload the package to the artchivematica externals repo, and we can close this bug

**Comment by mamedin** [comment] 2018-01-05 12:21
Another option is to change the `md5deep`, `sha265deep` and `sha1deep` calls in the fileCheckMD5NoGUI.sh file to the corresponding hashdeep form:

hashdeep -c md5
hashdeep -c sha256
hashdeep -c sha1

**Comment by sallain** [comment] 2018-01-08 21:04
As this now works on the test servers, I'm going to close the issue - perhaps a different issue should be filed without a 1.7 milestone if there's a plan to change the code.

Thanks!

**Comment by sevein** [comment] 2018-03-08 15:25
The issue wasn't reproducible because of that workaround that @scollazo applied on the QA server. I think that we should wait until https://github.com/artefactual-labs/am-packbuild/pull/105 is merged and the package is installed? I see in osdeps that we're only trying to install md5deep.

**Comment by kellyannewithane** [comment] 2018-04-30 20:44
Tested again to double-check with no errors.  Closing issue.

**Closed by kellyannewithane** 2018-04-30 20:44 UTC
Labels: bug, critical
