### ISSUE TITLE
Problem: Extract contents crashes due to UnicodeEncodeError 

### ISSUE THREAD

**Issue by kerim1** [artefactual/archivematica#1104] opened 2018-05-22 12:53 UTC
We have come across a transfer where the "Extract contents from compressed archives" job seems to run fine, until it comes across a new compressed object where it fails with the following message in the task overview in the dashboard:
```
....
Not extracting contents from Cotu_K.doc  - No rule found to extract
Not extracting contents from UMT_24.02.12.pdf  - No rule found to extract
Not extracting contents from Rapport_d_activite_Alen.niger_version2.doc  - No rule found to extract
Not extracting contents from Wawan_10.04.17.pdf  - No rule found to extract

extractContents.py: INFO      2018-05-17 20:56:32,786  archivematica.mcp.client.extractContents:get_dir_uuids:240:  Assigning UUID d425717b-eadf-45fc-b5d7-ab13cf550682 to directory path %transferDirectory%objects/SEMINAIRES_2010/MID_TERM_EVALUATION/revised_ghislaine.zip-2018-05-17T20:54:14.968039+00:00/
Traceback (most recent call last):
  File "/usr/lib/archivematica/MCPClient/clientScripts/extractContents.py", line 188, in <module>
    sys.exit(main(transfer_uuid, sip_directory, date, task_uuid, delete=delete))
  File "/usr/lib/archivematica/MCPClient/clientScripts/extractContents.py", line 164, in main
    transfer_mdl)
  File "/usr/share/archivematica/dashboard/main/models.py", line 502, in create_many
    for dir_path, dir_uuid in dir_paths_uuids])
  File "/usr/lib/archivematica/archivematicaCommon/archivematicaFunctions.py", line 237, in get_dir_uuids
    dir_uuid, dir_path)
UnicodeEncodeError: 'ascii' codec can't encode character u'\x82' in position 119: ordinal not in range(128)
```

The script crashes here, with an exit code of 1 according to the task overview dashboard. In the Transfer dashboard however, the job is incorrectly marked as 'Completed successfully'. 

Furthermore, it seems to have skipped the jobs 'Sanitize extracted objects' file and directory names', 'Scan for viruses on extracted files', etc. that would normally run after extraction of packages. Instead it simply moves forward to the 'Update METS.xml document' as if no packages to extract were found. 

This finally results in a 'real' error during METS creation during ingest:
```
Traceback (most recent call last):
  File "/usr/lib/archivematica/MCPClient/clientScripts/archivematicaCreateMETS2.py", line 1314, in <module>
    baseDirectoryPath, objectsDirectoryPath, directories)
  File "/usr/lib/archivematica/MCPClient/clientScripts/archivematicaCreateMETS2.py", line 1182, in get_normative_structmap
    add_normative_structmap_div(all_fsitems, normativeStructMapDiv, directories)
  File "/usr/lib/archivematica/MCPClient/clientScripts/archivematicaCreateMETS2.py", line 1220, in add_normative_structmap_div
    LABEL=basename)
  File "src/lxml/lxml.etree.pyx", line 3112, in lxml.etree.SubElement (src/lxml/lxml.etree.c:81786)
  File "src/lxml/apihelpers.pxi", line 203, in lxml.etree._makeSubElement (src/lxml/lxml.etree.c:18358)
  File "src/lxml/apihelpers.pxi", line 198, in lxml.etree._makeSubElement (src/lxml/lxml.etree.c:18281)
  File "src/lxml/apihelpers.pxi", line 302, in lxml.etree._initNodeAttributes (src/lxml/lxml.etree.c:19840)
  File "src/lxml/apihelpers.pxi", line 316, in lxml.etree._addAttributeToNode (src/lxml/lxml.etree.c:20196)
  File "src/lxml/apihelpers.pxi", line 1439, in lxml.etree._utf8 (src/lxml/lxml.etree.c:32441)
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
```
Further investigation into this error reveals it failed to insert the filename of an extracted file into a normative structmap, due to the fact that the file was of course never normalized after extraction.

**Comment by ross-spencer** [comment] 2018-05-22 14:41
@kerim1 can you provide a little more information about the structure of the transfer directory and the filenames, maybe via the `$ tree` command? I am trying something like this:
```
e-zip/
├── e-zip
│   ├── 4-23-PBé.pdf
│   ├── cé 2013.txt
│   ├── é2018-01-23é.png
│   └── édcé.doc
└── e-zip.7z
```
Where the 7z file underneath just contains a copy of the other objects in the directory, but I'm not seeing an error. 

I'll try some other compressed objects too.

**Comment by kerim1** [comment] 2018-05-23 08:11
It's a pretty big transfer, but I will try to fish out the package that is causing the issue.

**Comment by ross-spencer** [comment] 2018-05-23 08:44
Thanks @kerim1

**Comment by kerim1** [comment] 2018-05-24 07:17
The problematic zip package is called `révised ghislaine.zip` Here the complete output from the extract script:
```
7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
p7zip Version 9.20 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,16 CPUs)

Processing archive: /data/work/sharedDirectory/01/watchedDirectories/workFlowDecisions/extractPackagesChoice/zipped-unicode-test-4158cb50-e6d8-4b4b-9d20-ffdda70cd8aa/objects/revised_ghislaine.zip

Extracting  rvised ghislaine/Mid-term review and partners meeting - draft 3 GF edit_revised25nov.doc
Extracting  rvised ghislaine/TUC BUDGET MID TERM EVALUATION_REVISED.2xlsx25novebre.xlsx

Everything is Ok

Files: 2
Size:       120732
Compressed: 34041

Extracted contents from revised_ghislaine.zip
Assigning new file UUID: 0bc27d0a-3f6b-46f4-a058-ea581cbf6db0 to file /data/work/sharedDirectory/01/watchedDirectories/workFlowDecisions/extractPackagesChoice/zipped-unicode-test-4158cb50-e6d8-4b4b-9d20-ffdda70cd8aa/objects/revised_ghislaine.zip-2018-05-23T08:58:27.849417+00:00/rvised ghislaine/Mid-term review and partners meeting - draft 3 GF edit_revised25nov.doc
Assigning new file UUID: 856a3050-12c2-4854-a9e0-84fea40c97a8 to file /data/work/sharedDirectory/01/watchedDirectories/workFlowDecisions/extractPackagesChoice/zipped-unicode-test-4158cb50-e6d8-4b4b-9d20-ffdda70cd8aa/objects/revised_ghislaine.zip-2018-05-23T08:58:27.849417+00:00/rvised ghislaine/TUC BUDGET MID TERM EVALUATION_REVISED.2xlsx25novebre.xlsx
Assigning UUID 179e361b-a674-4585-b4d3-dae4e84829f2 to directory path %transferDirectory%objects/revised_ghislaine.zip-2018-05-23T08:58:27.849417+00:00/ 
```
```
Deleting?: True

extractContents.py: INFO      2018-05-23 08:58:28,636  archivematica.mcp.client.extractContents:get_dir_uuids:240:  Assigning UUID 179e361b-a674-4585-b4d3-dae4e84829f2 to directory path %transferDirectory%objects/revised_ghislaine.zip-2018-05-23T08:58:27.849417+00:00/
Traceback (most recent call last):
  File "/usr/lib/archivematica/MCPClient/clientScripts/extractContents.py", line 188, in <module>
    sys.exit(main(transfer_uuid, sip_directory, date, task_uuid, delete=delete))
  File "/usr/lib/archivematica/MCPClient/clientScripts/extractContents.py", line 164, in main
    transfer_mdl)
  File "/usr/share/archivematica/dashboard/main/models.py", line 502, in create_many
    for dir_path, dir_uuid in dir_paths_uuids])
  File "/usr/lib/archivematica/archivematicaCommon/archivematicaFunctions.py", line 237, in get_dir_uuids
    dir_uuid, dir_path)
UnicodeEncodeError: 'ascii' codec can't encode character u'\x82' in position 83: ordinal not in range(128)
```

The problem lies with the parent folder within the zip, which happens to have the same name as the zip itself. It looks like a character encoding problem. I've tried various unzipping tools and they all produce different folder names; all having problems with the accented e. The 'unzip' tool even doesn't allow it:
```
checkdir error:  cannot create r?vised ghislaine
                 Illegal byte sequence
```
Unzipping on a Windows machine gave the expected results though.

So the problem is with the zip itself, however, we'd expect Archivematica to complain about it, instead of continuing and then failing during METS creation because of it. I've tried to recreate the zip file with some dummy data. (I'll send it to you by email?) However, for some reason the transfer now fails during the clean up names phase:
```
sanitizeObjectNames.py: INFO      2018-05-24 07:15:17,046  archivematica.mcp.client.sanitizeObjectNames:sanitize_object_names:59:  sanitizations: /data/work/sharedDirectory/01/currentlyProcessing/zipped-unicode-test-3-407aa8ec-55a0-480f-824b-cbbfe67fd2e9/objects/révised ghislaine.zip -> /data/work/sharedDirectory/01/currentlyProcessing/zipped-unicode-test-3-407aa8ec-55a0-480f-824b-cbbfe67fd2e9/objects/revised_ghislaine.zip
sanitizeObjectNames.py: INFO      2018-05-24 07:15:17,048  archivematica.mcp.client.sanitizeObjectNames:sanitize_object_names:76:  Checking /data/work/sharedDirectory/01/currentlyProcessing/zipped-unicode-test-3-407aa8ec-55a0-480f-824b-cbbfe67fd2e9/objects/révised ghislaine.zip
sanitizeObjectNames.py: INFO      2018-05-24 07:15:17,048  archivematica.mcp.client.sanitizeObjectNames:sanitize_object_names:116:  Sanitized name: %transferDirectory%objects/révised ghislaine.zip -> %transferDirectory%objects/revised_ghislaine.zip
Traceback (most recent call last):
  File "/usr/lib/archivematica/MCPClient/clientScripts/sanitizeObjectNames.py", line 140, in <module>
    sanitize_object_names(objectsDirectory, sipUUID, date, groupType, groupSQL, sipPath)
  File "/usr/lib/archivematica/MCPClient/clientScripts/sanitizeObjectNames.py", line 119, in sanitize_object_names
    updateFileLocation(**kwargs)
  File "/usr/lib/archivematica/archivematicaCommon/fileOperations.py", line 217, in updateFileLocation
    f = File.objects.get(**kwargs)
  File "/usr/share/python/archivematica-mcp-client/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/share/python/archivematica-mcp-client/local/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
main.models.DoesNotExist: File matching query does not exist.
```

**Comment by ross-spencer** [comment] 2018-05-24 07:30
Thanks again @kerim1. Yep, please do send it by email to my Artefactual account. You are right, AM should definitely be complaining about it rather than failing. Let's see what I can come up with this end.

**Comment by ross-spencer** [comment] 2018-05-29 11:55
Hi @kerim1 do you have access to the MCP Client server for the pipeline that this is happening on? Can you let me know the output of `$ locale`?

**Comment by ross-spencer** [comment] 2018-05-29 14:34
For reference the Python codepage mapping: https://github.com/python/cpython/blob/73cbe7a01a22d02dbe1ec841e8779c775cad3d08/Lib/encodings/cp437.py#L50

**Comment by ross-spencer** [comment] 2018-05-30 16:46
I believe this Python 2 #wontfix is related: https://bugs.python.org/issue7300 - which is something we should think about when considering what we need to do to make this work Py3 compatible.

**Comment by kerim1** [comment] 2018-05-31 06:39
Good to hear that you managed to recreate the problem. It seems to be a much wider issue around various character encodings. 

I don't think you really need the output of `locale` anymore, but just in case:  
```
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

**Comment by ross-spencer** [comment] 2018-05-31 08:29
Thanks @kerim1 good to confirm. This is what we expect so all good. If locale didn't look like this, we'd see a similar error but a slightly different message. I think we're getting close to a first attempt at solution. I'm just investigating various trickle down effects as we speak.

**Comment by ross-spencer** [comment] 2018-05-31 08:30
The chainlink we need to lookup in the MCP Server to see more information about exit codes is: `select * from MicroServiceChainLinks where pk = '1cb7e228-6e94-4c93-bf70-430af99b9264'`

**Comment by ross-spencer** [comment] 2018-05-31 08:52
Okay, some more interesting behaviour. With the current configuration, you can supply the microservice with a very broken zip file (attached) and it will continue to process as well:

![image](https://user-images.githubusercontent.com/1880412/40772553-8ffe3b68-64c0-11e8-80d9-143a991eeb81.png)

I think this one might need teasing out a bit more.

Broken zip: [ascii_cp437.zip](https://github.com/artefactual/archivematica/files/2057476/ascii_cp437.zip)

**Comment by ross-spencer** [comment] 2018-05-31 09:30
When we fix this, we have to also consider DSpace Transfers: `select * from MicroServiceChainLinks where pk = 'bd792750-a55b-42e9-903a-8c898bb77df1'` this is the only other set of ChainLinks with its own 'Extract packages'

**Comment by ross-spencer** [comment] 2018-05-31 16:07
Hi @kerim1 I have submitted a [pull request](https://github.com/artefactual/archivematica/pull/1115) against this issue. There are two parts to it:

* Adds a [Unicode formatted string](https://github.com/artefactual/archivematica/pull/1115/commits/bec08e35d53d4660ced1d178bcd94a595bb40285#diff-838f8ec4e09d38f2be9db038af787422R236) to archivematicaCommonFunctions. This is what failed before and if we were to process your transfer again it won't fail, and the Transfer should be processed as expected.

* If the microservice experiences any other type of failure in future then it won't continue to the end. We will fall-back to 'failed transfer' and then it can be investigated more thoroughly. 

I have opened the PR to begin discussion.

There are still other questions that we can ask over a longer period of time:

* Should the extract packages work be done sooner in the process?
* How do we get on top of various character encoding issues?

Some of these questions we can talk about next meeting.

For IISH immediately, I wanted to check - is there anything we need to do with the SIP that caused the issue now? With Transfers of this type failing when they get to Ingest, I don't believe we're expecting to see other SIPs with this issue? Are you happy to run that particular transfer again?

**Comment by kerim1** [comment] 2018-07-16 14:34
We have tried again with our own test collection, but now it fails on the backtick again while assigning uuids to directories. See new issue here: https://github.com/archivematica/Issues/issues/16

**Comment by ross-spencer** [comment] 2018-08-18 23:41
This should be fixed re: the comments here: https://github.com/archivematica/Issues/issues/16#issuecomment-405802297 however we need to test this to confirm it on the current `qa/1.x` branch.

**Comment by peterVG** [comment] 2018-10-10 18:35
@ross-spencer Testing on AM18x Bionic using "TestTransfers/dirs_with_various_encodings" sample data, it is passing the "Extract contents from compressed archives" microservice with an exit code of 0 for each zip file but then reports a "Failure" on the 'Sanitize extracted objects' file and directory names' for each zip package file with an exit code of "none".
![screen shot 2018-10-10 at 11 31 42](https://user-images.githubusercontent.com/672121/46757873-44fb4c00-cc80-11e8-8415-2fc6a6b2148b.png)

**Comment by ross-spencer** [comment] 2018-10-11 19:55
Hi @peterVG, I think it was a different folder you were testing with from discussions in Slack, the `sample-zip-packages`. 

![image](https://user-images.githubusercontent.com/1880412/46829010-25d4eb00-cd62-11e8-8d4a-d270b897e447.png)
 
In the folder that you are testing with two sets of zips are specifically related to encoding issues. These should both pass, I have verified that for myself:

* http://am18bionic.qa.archivematica.org/transfer/7f77c5b5-dec1-450c-b898-f3fb497d9231/microservices/ 
* http://am18bionic.qa.archivematica.org/transfer/44ea646a-bb3b-44b2-9eeb-4955b993ad84/microservices/

But you might want to do the same. 

The deep-transfers folder fails. I think this is either a new issue, or related to: https://github.com/artefactual/archivematica/issues/789 you can verify that the deep transfer zip should have no non-ascii characters in there.

Partial output should look like this:

```
zipinfo deep_zip_transfer.zip 
Archive:  deep_zip_transfer.zip
Zip file size: 511220 bytes, number of entries: 1817
drwxr-xr-x  2.0 unx        0 b- stor 18-Oct-11 14:48 deep_zip_transfer/
drwxr-xr-x  2.0 unx        0 b- stor 18-Oct-11 14:48 deep_zip_transfer/00001/
drwxr-xr-x  2.0 unx        0 b- stor 18-Oct-11 14:48 deep_zip_transfer/00002/
drwxr-xr-x  2.0 unx        0 b- stor 18-Oct-11 14:48 deep_zip_transfer/00003/
-rw-r--r--  2.0 unx      181 b- defN 18-Oct-11 14:48 deep_zip_transfer/README.md
drwxr-xr-x  2.0 unx        0 b- stor 18-Oct-11 14:48 deep_zip_transfer/00002/00001/
drwxr-xr-x  2.0 unx        0 b- stor 18-Oct-11 14:48 deep_zip_transfer/00002/00002/
drwxr-xr-x  2.0 unx        0 b- stor 18-Oct-11 14:48 deep_zip_transfer/00002/00003/
-rw-r--r--  2.0 unx      181 b- defN 18-Oct-11 14:48 deep_zip_transfer/00002/00002.md
-rw-r--r--  2.0 unx      181 b- defN 18-Oct-11 14:48 deep_zip_transfer/00002/00004.md
-rw-r--r--  2.0 unx      181 b- defN 18-Oct-11 14:48 deep_zip_transfer/00002/00001.md
-rw-r--r--  2.0 unx      181 b- defN 18-Oct-11 14:48 deep_zip_transfer/00002/00003.md
```

It is hard to tell whether it is a new issue or not without stderr output so I will try and look at the logs on bionic as well. 

**NB.** I have spotted a potential issue with these sample zip files which I am just waiting for access to bionic to confirm. I'll log an issue and relate it back to here asap. (The issue is that we're accidentally zipping existing zips every time we run the `createtransfer.py` script so we're exponentially (I think) increasing the size of these auto-generated transfers every time we run it!)

**Comment by ross-spencer** [comment] 2018-10-11 20:32
Issue related to creating the sample transfers mentioned above: https://github.com/archivematica/Issues/issues/268

**Comment by peterVG** [comment] 2018-10-11 21:04
Yes, confirmed. The encoded files and encoded directories sets of zips are passing successfully. It is the deep-transfer zip that is still causing the same error.

![screen shot 2018-10-11 at 14 03 52](https://user-images.githubusercontent.com/672121/46833856-8eba6400-cd5e-11e8-8e44-a3bbbb9c056c.png)

**Closed** 2018-11-22 16:10 UTC
Labels: IISH, Status: verified
