### ISSUE TITLE
Problem: Verify SSL certificates in Handle server config defaults back to checked

### ISSUE THREAD

**Issue by sromkey** [artefactual/archivematica#834] opened 2017-12-11 21:38 UTC
When you have unchecked the "Verify SSL certificates" box on the Handle server config page, it appears to have saved. However, if you then navigate away from the page and come back, it is checked again.

**Comment by jrwdunham** [comment] 2017-12-15 00:57
Should be fixed by https://github.com/artefactual/archivematica/pull/847.

**Comment by jrwdunham** [comment] 2017-12-15 02:06
The underlying issue was caused by the fact that the `pid_request_verify_certs` field/attribute of the Handle config settings, which is stored as a DashboardSetting instance/row, is a boolean yet the dashboard settings key/value pairs are untyped (are implicitly strings). Therefore that setting was being passed to the template as the truthy string `'False'`, which caused the HTML checkbox to incorrectly have `checked="checked"`.

A more general fix than that provided in https://github.com/artefactual/archivematica/pull/847 would add type information to the dashboard settings table (or assume the value column is JSON, which would be parsed to Python).

**Comment by jrwdunham** [comment] 2017-12-15 21:54
Closing this. If not fixed by https://github.com/artefactual/archivematica/pull/847 this can be reopened.

**Closed by jrwdunham** 2017-12-15 21:54 UTC
Labels: bug
