### ISSUE TITLE
Problem: re-ingest fails with service files

### ISSUE THREAD

**Issue by jrwdunham** [artefactual/archivematica#1151] opened 2018-06-20 18:28 UTC
A `RuntimeError: maximum recursion depth exceeded` error will be raised in the "Generate METS.xml document" micro-service when attempting a re-ingest of an AIP containing service files. This is in turn caused by an issue in mets-reader-writer: https://github.com/artefactual-labs/mets-reader-writer/issues/37.

Note: recent attempts (2018-06) to re-create this issue have failed.

Related to https://github.com/artefactual/archivematica-storage-service/issues/317

**Comment by jrwdunham** [comment] 2018-06-20 19:46
I have failed to re-create this issue using the following three methods. I am going to close it but suspect it may still be present but hidden somehow.

I tried the following with all three **reingest-types**: **metadata-only**, **partial**, and **full**:

1. Create an AIP from SampleData/DigitizationOutput/ (which contains service files).
2. Verify that USE=service files are documented in the AIP METS.
3. Do a **reingest_type** re-ingest on the resulting AIP.
4. Expect to see a failure at "Generate METS.xml document".
5. Do not see a failure and be sad and happy at the same time.

**Comment by nickwilkinson** [comment] 2018-07-12 20:56
![](https://github.trello.services/images/mini-trello-icon.png) [Artefactual (internal)](https://trello.com/c/AxNvL2Bv/11-artefactual-internal)

**Comment by sromkey** [comment] 2018-08-22 19:50
I'm taking the milestone off of this since it wasn't so much fixed as not reproduced. Also closing the issue.

**Closed by sromkey** 2018-08-22 19:50 UTC
Labels: Status: verified, Type: bug
