### ISSUE TITLE
MCPClient should check for exceptions when creating Gearman worker

### ISSUE THREAD

**Issue by minusdavid** [artefactual/archivematica#673] opened 2017-07-12 05:24 UTC
When constructing the Gearman worker in startThread() in /usr/lib/archivematica/MCPClient/archivematicaClient.py, there should be exception checking. 

If the config item MCPArchivematicaServer has an invalid value, the worker won't run, and Archivematica will be stuck thinking the task is executing indefinitely with no indication of what's happened in the user interface or the logs.

**Comment by sevein** [comment] 2017-07-12 18:55
@minusdavid is addressing this issue here: #674.

**Comment by minusdavid** [comment] 2017-07-13 00:29
Thanks, @sevein! I meant to add that link but ran out of time last night.

**Comment by sevein** [comment] 2017-09-25 17:46
@minusdavid, I've been trying to reproduce this issue without success. I even tried to raise my own exceptions from the threaded functions from different places, e.g.:

```
@auto_close_db
def startThread(threadNumber):
    """Setup a gearman client, for the thread."""
    #
    #
    raise Exception("foobar")
    #
    #
    gm_worker = gearman.GearmanWorker([django_settings.GEARMAN_SERVER])
    hostID = gethostname() + "_" + threadNumber.__str__()
    gm_worker.set_client_id(hostID)
    for key in supportedModules.keys():
        logger.info('Registering: %s', key)
        gm_worker.register_task(key, executeCommand)

    failMaxSleep = 30
    failSleep = 1
    failSleepIncrementor = 2
    while True:
        try:
            gm_worker.work()
        except gearman.errors.ServerUnavailable as inst:
            logger.error('Gearman server is unavailable: %s. Retrying in %d seconds.', inst.args, failSleep)
            time.sleep(failSleep)
            if failSleep < failMaxSleep:
                failSleep += failSleepIncrementor
```

The exceptions are being logged. Maybe this is because of the recent changes we've done to the logger in `qa/1.7.x`.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django_mysqlpool/__init__.py", line 10, in wrapper
    return f(*args, **kwargs)
  File "/src/MCPClient/lib/archivematicaClient.py", line 149, in startThread
    raise Exception("foobar")
Exception: foobar

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django_mysqlpool/__init__.py", line 10, in wrapper
    return f(*args, **kwargs)
  File "/src/MCPClient/lib/archivematicaClient.py", line 149, in startThread
    raise Exception("foobar")
Exception: foobar
```

It's logged twice because I have two threads running in parallel.

I'm going to close this issue but please if you find a way to reproduce this issue please let me know how and I'll reopen it! Thank you so much.

**Closed by sevein** 2017-09-25 17:46 UTC

**Comment by minusdavid** [comment] 2017-09-27 07:45
No worries. My apologies for not following up on my issues more. I've been too preoccupied with other work, alas.
