### ISSUE TITLE
Problem: Can't start large transfers

### ISSUE THREAD

**Issue by jhsimpson** [artefactual/archivematica#645] opened 2017-06-16 23:16 UTC
As discussed in this google group thread: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/archivematica-tech/jADMHfVVUHY/vFPt4wvdAAAJ

in the qa/1.x branch, this line:
https://github.com/artefactual/archivematica/blob/qa/1.x/src/archivematicaCommon/lib/storageService.py#L57

appears to be causing a problem.  The problem occurs when a transfer is started in the dashboard (either by calling the start_transfer() rest api endpoint, or by clicking the 'start transfer' button in the transfer tab of the dashboard.  This causes the dashboard to make a rest call to the storage service, asking it to copy files from a specified Transfer Source Location to the pipeline.  This can take a long time for large files, minutes or hours potentially.

Having a timeout of 5 seconds or 120 seconds causes an error like the one shown in the google group.

**Comment by sevein** [comment] 2017-10-11 14:41
Fixed in https://github.com/artefactual/archivematica/pull/747.

**Closed by sevein** 2017-10-11 14:41 UTC
Labels: bug, critical

**Comment by sromkey** [comment] 2018-02-21 17:50
This is a duplicate of #712
